#!/bin/bash

for first in {a..z}; do
    for second in {a..z}; do
        combination="${first}${second}"
        if [ "$combination" != "oo" ]; then
            echo "$combination"
        fi
    done
done
